// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todos;

namespace todos.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20210326141640_SwitchedUsernametoOwner")]
    partial class SwitchedUsernametoOwner
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("todos.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "carlos@wecancodeit.org",
                            Name = "Carlos"
                        },
                        new
                        {
                            Id = 2,
                            Email = "davis@wecancodeit.org",
                            Name = "Davis"
                        });
                });

            modelBuilder.Entity("todos.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueBy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sample todo item 1",
                            CreatedOn = new DateTime(2021, 3, 26, 10, 16, 39, 808, DateTimeKind.Local).AddTicks(3832),
                            DueBy = new DateTime(2021, 3, 31, 10, 16, 39, 814, DateTimeKind.Local).AddTicks(5993),
                            IsDone = false,
                            Name = "Test Todo 1",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sample todo item 2",
                            CreatedOn = new DateTime(2021, 3, 26, 10, 16, 39, 814, DateTimeKind.Local).AddTicks(8134),
                            DueBy = new DateTime(2021, 3, 31, 10, 16, 39, 814, DateTimeKind.Local).AddTicks(8201),
                            IsDone = false,
                            Name = "Test Todo 2",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Sample todo item 3",
                            CreatedOn = new DateTime(2021, 3, 26, 10, 16, 39, 814, DateTimeKind.Local).AddTicks(8233),
                            DueBy = new DateTime(2021, 3, 31, 10, 16, 39, 814, DateTimeKind.Local).AddTicks(8240),
                            IsDone = false,
                            Name = "Test Todo 3",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("todos.Models.Todo", b =>
                {
                    b.HasOne("todos.Models.Owner", "Owner")
                        .WithMany("Todos")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
