// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todos;

namespace todos.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20210323180457_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("todos.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueBy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sample todo item 1",
                            CreatedOn = new DateTime(2021, 3, 23, 14, 4, 55, 991, DateTimeKind.Local).AddTicks(1873),
                            DueBy = new DateTime(2021, 3, 28, 14, 4, 55, 997, DateTimeKind.Local).AddTicks(8558),
                            IsDone = false,
                            Name = "Test Todo 1",
                            Username = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sample todo item 2",
                            CreatedOn = new DateTime(2021, 3, 23, 14, 4, 55, 999, DateTimeKind.Local).AddTicks(139),
                            DueBy = new DateTime(2021, 3, 28, 14, 4, 55, 999, DateTimeKind.Local).AddTicks(277),
                            IsDone = false,
                            Name = "Test Todo 2",
                            Username = "SYSTEM"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Sample todo item 3",
                            CreatedOn = new DateTime(2021, 3, 23, 14, 4, 55, 999, DateTimeKind.Local).AddTicks(307),
                            DueBy = new DateTime(2021, 3, 28, 14, 4, 55, 999, DateTimeKind.Local).AddTicks(313),
                            IsDone = false,
                            Name = "Test Todo 3",
                            Username = "SYSTEM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
